### ISSUE TITLE
psycopg Programming Error (?)

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#305] opened 2019-05-21 05:50 UTC
Project generation with QGIS 3.4.7 and ModelBaker 4.2.2 throws an error upon try:

`Ein Fehler trat bei der Ausführung von Python-Code auf: 

psycopg2.ProgrammingError: column full_name.owner does not exist LINE 27:                                        ON full_name.owner='...                                                     ^ 
Traceback (most recent call last):
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\generate_project.py", line 285, in accepted
    available_layers = generator.layers()
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\generator\generator.py", line 121, in layers
    fields_info = self.get_fields_info(record['tablename'])
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\generator\generator.py", line 292, in get_fields_info
    return self._db_connector.get_fields_info(table_name)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\pg_connector.py", line 298, in get_fields_info
    full_name_join=full_name_join))
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\psycopg2\extras.py", line 144, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: column full_name.owner does not exist
LINE 27:                                         ON full_name.owner='...
                                                    ^`

Seems pretty much like a showstopper to me...
Any immediate suggestions? Re-installing the plugin did not help.

**Comment by m-kuhn** [comment] 2019-05-21 05:54
Was ili2db4 involved in any way? From what I remember, I had this error in combination with ili2db4.

**Comment by zigertiger** [comment] 2019-05-21 06:00
... I use both 4.1.0 and 3.12.2.
But in this particular case, ili2db was not involved at all (?) since I was trying to generate a QGIS project out of an existing PostGIS schema...

**Comment by m-kuhn** [comment] 2019-05-21 06:47
I need to verify, but that should work. First guess would be that there are some leftovers of earlier ili2db 4 data in this schema, that make model baker looks for ili2db related information.
If this rings a bell, let me know. If not, can you send me a dump of this schema?

**Comment by pramisters** [comment] 2019-05-21 07:21
I had the same problem when generating directly from PostGIS.
See #304.
And yes, could be related to a previous schema generation with ili2db 4.x

**Comment by zigertiger** [comment] 2019-05-21 09:40
OK...
Anyway, we absolutely need to be able to work wird ili2pg4-generated schemas.

(We need to work with ili2pg4 because of export according federal models.

**Comment by m-kuhn** [comment] 2019-09-18 11:53
Duplicate of #304

**Closed by m-kuhn** 2019-09-18 11:53 UTC
