### ISSUE TITLE
Issue while scanning all schemas in my postgis database

### ISSUE THREAD

**Issue by Gustry** [opengisch/QgisModelBaker#199] opened 2018-05-17 19:48 UTC
I'm trying to scan all schemas in my postgis database:
![screenshot from 2018-05-17 14-38-12](https://user-images.githubusercontent.com/1609292/40200025-2ff1636c-59e9-11e8-90d7-e2a42999362d.png)

The placeholder for the schema is:
> Leave empty to load all schemas in the database

So I understood that it will scan all schemas in the database but I have the error:
> Source schema does not exist. Check connection parameters.

It seems a bug to me.

PS: It would be very nice to have each schema in a group in the legend. I have 30 schemas in my database.

Thanks for this tool.

CC @3nids

**Comment by gacarrillor** [comment] 2018-05-17 19:53
Documentation in the code (and placeholder in the GUI you posted) are out of date. The current behaviour is to deal with single input schemas.

**Comment by m-kuhn** [comment] 2018-05-18 04:58
I wouldn't have any issues with restoring the original intended behaviour and the groups for schemas in the layer tree.

**Comment by tjukanovt** [comment] 2021-07-23 10:52
@m-kuhn What is the status on the "all schemas" functionality? Is it still missing a sponsor or what is the plan with that?

**Comment by m-kuhn** [comment] 2021-07-23 11:16
This project pretty much focused and focuses on improving interlis compatibility, there are currently no plans to work on the interlis-less front. If someone commits to improving this with a pull request or sponsoring, that's very welcome.

**Comment by Gustry** [comment] 2021-07-23 12:45
Up to you if you want to keep this ticket open or not. Fine to close for me. THanks

**Comment by m-kuhn** [comment] 2021-07-23 12:48
As a quick fix we could at least remove the misleading placeholder text

**Comment by tjukanovt** [comment] 2021-07-27 05:48
Ok. Cool. Let's keep the ticket open as we would benefit a lot from this feature here at Gispo so let's see if we could develop this ourself.

**Comment by signedav** [comment] 2022-04-20 06:42
I plan to:
- [ ] Fix the text quickly
- [ ] Close this since we can make this #456 instead on export, generate and data import

**Closed** 2022-04-20 12:31 UTC
