### ISSUE TITLE
NOT NULL Constraints im Formular

### ISSUE THREAD

**Issue by pramisters** [opengisch/QgisModelBaker#40] opened 2017-05-04 16:49 UTC
Die NOT NULL-Constraints sind beim Widget "Texteditor" zwar konfiguriert (Haken bei "Nicht Null" unter "Restriktionen" gesetzt (warum ausgegraut ?), im Formular fehlt aber die Warnmeldung und OK ist aktiv. Beim Widget "Bereich" funktionierts (rot eingefärbtes Feld, Warnmeldung und OK inaktiv).

**Comment by m-kuhn** [comment] 2017-05-04 17:00
Ausgegraut weil in der Datenbank gesetzt (darum macht es keinen Sinn, dem User zu erlauben, diesen zu deaktivieren)

**Comment by m-kuhn** [comment] 2017-08-23 13:27
> Matthias lo resolvió en https://github.com/qgis/QGIS/pull/4739
> <https://github.com/qgis/QGIS/pull/4739>
> Sin embargo, consideramos con Sergio que dicha solución es parcial,
> puesto que el manejo de NULLs no es del todo claro para el usuario. Por
> ejemplo, si un campo está vacío en el formulario, el validador dice que
> el CHECK pasa sin errores. En la imagen siguiente, la columna Tipo tiene
> un valor vacío, sin embargo el CHECK NOT NULL pasa y muestra un chulito
> verde.

**Comment by m-kuhn** [comment] 2017-08-23 13:28
@gacarrillor can you paste this picture here - and possibly provide test data to reproduce this? Thanks

**Comment by gacarrillor** [comment] 2017-08-24 13:01
This is a QGIS issue. Look at the field `tipo`. It's empty but passed the NOT NULL check. The only way the check fails again is writing "NULL", which is a bit weird. It happens to me with text fields.

Just as an idea, wouldn't be more appropriate to have such "NULL" string as a placeholder text?

![not_null_check](https://user-images.githubusercontent.com/652785/29667361-b48e9e60-88a1-11e7-9d98-06147502bf8d.png)

**Comment by m-kuhn** [comment] 2017-08-24 13:03
Can you pass me the ili file?

Yes, placeholder sounds great, but it will completely prevent anyone from entering an empty string, no?

**Comment by gacarrillor** [comment] 2017-08-24 13:13
It should be reproducible loading a PostgreSQL table with text fields and opening its form in QGIS.

> Yes, placeholder sounds great, but it will completely prevent anyone from entering an empty string, no?

Anyway, if you leave the field empty and attempt to save, the server says you cannot save because it gets a NULL value for that field.

**Comment by m-kuhn** [comment] 2017-08-24 13:24
> Anyway, if you leave the field empty and attempt to save, the server says you cannot save because it gets a NULL value for that field.

I understood that the proposal is for QGIS to always interpret empty text as NULL value.
In this case it would never be possible to save an empty text as an empty (non NULL) text. Did I get something wrong?

**Comment by gacarrillor** [comment] 2017-08-24 13:35
> I understood that the proposal is for QGIS to always interpret empty text as NULL value.

That's how it partially is right now. As I told you, if you leave the field empty, client validation passes (empty string != NULL) but QGIS sends a NULL value to server anyways. So the issue here is also lack of consistency.

Couldn't this be discussed with the community?

**Comment by m-kuhn** [comment] 2017-08-24 13:45
> So the issue here is also lack of consistency.

Totally sounds so, that should be fixed then, this makes no sense.

I agree that in general, someone normally wants to set a field to `NULL` and far less often to `''`. In QGIS however it is way easier to set it to an empty string (press backspace) than to `NULL` (type NULL or use the mouse to click the delete symbol).

I wonder if it's possible to find an easy way to reset the value to NULL without preventing entering an empty string. Like pressing backspace on an empty field will toggle between empty text / NULL.

> Couldn't this be discussed with the community?

Of course :)

**Comment by gacarrillor** [comment] 2017-10-23 21:23
Hi Matthias, we (Sergio and I) gave this a second thought. 

We consider that the following changes would make `NULL` handling in forms more intuitive and predictable:
 
 + If the field is a String and is left empty in a form, QGIS should send an empty string to the database, not a `NULL`. In this scenario, QGIS currently sends a `NULL` value for PostgreSQL and an empty string for GeoPackage.
 + As soon as a string field in a form gets the focus (and it has a `NULL` value), the `NULL` value shouldn't bother users. `NULL` should be removed from the form field. 

So, by default, untouched fields will be sent by QGIS as `NULL` values (well, unless they have been configured with default values) and if a user wants to send `NULL` values to the database, she should write the word `NULL` (or whatever is configured as QGIS `NULL` value).

What do you think?

**Comment by m-kuhn** [comment] 2018-03-10 14:11
I think 99% of the time, one wants a NULL value, so it should be very easy for everyone to insert a NULL value. An empty string should be possible, but quite a bit harder to do.

What I could imagine is that the line edit has two states, one for `NULL` and one for `''`, and you can toggle between the two states with some interaction

 * By default deleting the content will set the placeholder text of the widget to `NULL`
 * The user can switch to empty string mode by long clicking the "clear field" button or double-backspace. If the widget is in this mode it will show "Empty String (quickly press backspace twice for NULL)" as placeholder text
 * And have a good tooltip for what it's worth

@3nids @gacarrillor @seralra96 what do you think about that?

**Comment by gacarrillor** [comment] 2018-03-12 14:13
@m-kuhn I like that approach. Please keep in mind to make sure it is "consistent" (see https://github.com/opengisch/projectgenerator/issues/40#issuecomment-324636916), that is, client validation and what QGIS sends to the database should deal with the value equally. Also, please make users life easier by avoiding values like `NULLmyvalue` (see second bullet point in https://github.com/opengisch/projectgenerator/issues/40#issuecomment-338800904).

**Comment by signedav** [comment] 2021-06-29 06:17
Is this solved?

- The "NULL" representation issue is noted in this https://github.com/qgis/QGIS/issues/22883 issue and fixed
- With a quick test I experienced that when saving NULL, then NULL is saved and when saving an empty string an empty string is saved. I create an empty string in  the form by deleting the text and I set it  back to null with the small arrow at the end of the text edit widget.
![image](https://user-images.githubusercontent.com/28384354/123746791-667a4700-d8b2-11eb-844a-9c00c8bf7f5f.png)

**Comment by gacarrillor** [comment] 2021-06-29 14:07
Yes, it seems this is fixed now. I'll reopen if notice this behavior again.

**Comment by signedav** [comment] 2021-06-29 14:09
Thanks.

**Closed** 2021-06-29 14:08 UTC
Labels: offer_requested

**Comment by gacarrillor** [comment] 2021-06-29 14:21
Thank you @signedav

**Comment by m-kuhn** [comment] 2021-07-08 16:21
I think there is still an improvement possible, currently "backspace" will set the field to empty (and therefore bypassing the not null check) while normally you'd expect it to set it to NULL for the not null constraint to trigger. Proposal: first backspace when there is content (or it's empty) -> set it to null, second backspace (when null) -> set it to empty.
